---
- name: "prepare variables for monitoring"
  set_fact:
    key_value: "yes"
    nvidia_monitoring: |
      nvidia:
          runtime: nvidia
          image: nvidia/dcgm-exporter:2.1.4-2.3.1-ubuntu18.04
          container_name: monitoring_nvidia
          privileged: true
          restart: unless-stopped
          expose:
            - 9400
          #ports:
          #  - 9400:9400
    nvidia_depends: "- nvidia"
    prometheus_nvidia: "- 'monitoring_nvidia:9400'"
  when: (use_gpu | bool)

- name: Create directory for monitoring
  file:
    path: /usr/local/share/dodasts/monitoring
    state: directory
    mode: 0755

- name: Create directory for prometheus
  file:
    path: /usr/local/share/dodasts/monitoring/prometheus
    state: directory
    mode: 0755

- name: Create directory for prometheus config
  file:
    path: /usr/local/share/dodasts/monitoring/prometheus/config
    state: directory
    mode: 0755

- name: Create directory for prometheus data
  file:
    path: /usr/local/share/dodasts/monitoring/prometheus/data
    state: directory
    owner: nobody
    group: nogroup
    mode: 0755

- name: Create prometheus config for monitoring from template
  template:
    src: prometheus.yml.j2
    dest: /usr/local/share/dodasts/monitoring/prometheus/config/prometheus.yml
